### ISSUE TITLE
Why this is happening if i am using toolbar without toolbar its working fine.

### ISSUE THREAD

**Issue by mohittanwar94** [vikramkakkar/ImageTransition#3]
java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
                                                                                  at com.appeaser.imagetransitionlibrary.ImageTransitionCompatHelper.createAnimator(ImageTransitionCompatHelper.java:67)
                                                                                  at com.appeaser.imagetransitionlibrary.ImageTransition.createAnimator(ImageTransition.java:69)
                                                                                  at android.transition.Transition.createAnimators(Transition.java:732)
                                                                                  at android.transition.TransitionSet.createAnimators(TransitionSet.java:405)
                                                                                  at android.transition.TransitionSet.createAnimators(TransitionSet.java:405)
                                                                                  at android.transition.Transition.playTransition(Transition.java:1777)
                                                                                  at android.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:308)
                                                                                  at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2417)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6708)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:696)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                  at android.os.Looper.loop(Looper.java:207)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

please reply why this is happening .........

**Comment by mohittanwar94** [comment]
that was resolve its happening due to coordinator layout in toolbar after converting  coordinator layout int o frame layout .

thank you.

**Comment by vikramkakkar** [comment]
Ideally, `ImageTransitionLibrary` should be layout-agnostic. Can you please provide the layout xml and relevant activity code that was causing the crash?

**Comment by mohittanwar94** [comment]
actually i was using coordinator layout inside toolbar when i pass
transition view as an image view but after that i debug and found
internally coordinator layout is going inside create animator instead of
image view.after that i change coordinator layout into frame layout .every
thing is working perfect .
here is my toolbar layout put it inside your sample and test it.





<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.Toolbar
xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    android:background="@color/teacherheader"
    android:clipChildren="false"
    android:contentInsetLeft="0dp"
    android:contentInsetRight="0dp"
    android:contentInsetStart="0dp"
    android:elevation="@dimen/size_5"
    android:padding="0dp"
    android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
    android:titleTextColor="@color/white"
    app:contentInsetLeft="0dp"
    app:contentInsetRight="0dp"
    app:contentInsetStart="0dp"
    app:popupTheme="@style/ThemeOverlay.AppCompat.Light">


    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipChildren="false">

        <com.varshylmobile.snaphomework.customviews.SnapTextView
            android:id="@+id/headertext"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:layout_centerVertical="true"
            android:drawablePadding="@dimen/size_5"
            android:ellipsize="end"
            android:gravity="center"
            android:maxLines="1"
            android:textColor="@android:color/white"
            android:textSize="@dimen/size_16_dot_67"
            app:textFont="GOTHAM_LIGHT" />


        <ImageView
            android:id="@+id/leftIcon"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_centerVertical="true"
            android:background="?attr/selectableItemBackgroundBorderless"
            android:paddingBottom="@dimen/size_15"
            android:paddingLeft="@dimen/size_20"
            android:paddingRight="@dimen/size_20"
            android:paddingTop="@dimen/size_15"
            android:src="@drawable/back_new"
            android:text="@string/done"
            android:visibility="visible" />

        <LinearLayout
            android:id="@+id/headertextLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_toLeftOf="@+id/rightIcon"
            android:layout_toRightOf="@+id/leftIcon"
            android:orientation="horizontal"
            android:visibility="gone">

            <com.varshylmobile.snaphomework.customviews.SnapTextView
                android:id="@+id/activitytext"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_gravity="left"
                android:layout_weight="2"
                android:background="@drawable/tip_header_student"
                android:gravity="left|center"
                android:paddingLeft="@dimen/size_15"
                android:text="@string/activity"
                android:textColor="@color/white"
                android:textSize="@dimen/size_16_dot_67"
                app:textFont="GOTHAM_BOLD" />

            <com.varshylmobile.snaphomework.customviews.SnapTextView
                android:id="@+id/celebertytext"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_gravity="center"
                android:layout_weight="1"
                android:gravity="center"
                android:text="@string/college_celeberity_program"
                android:textColor="@color/white"
                android:textSize="@dimen/size_16_dot_67"
                app:textFont="GOTHAM_BOLD" />

        </LinearLayout>

        <com.varshylmobile.snaphomework.customviews.SnapTextView
            android:id="@+id/done"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:drawablePadding="@dimen/size_5"
            android:gravity="center"
            android:padding="@dimen/size_15"
            android:text="@string/done"
            android:textColor="@color/white"
            android:visibility="gone"
            app:textFont="GOTHAM_BOLD" />


        <ImageView
            android:id="@+id/rightIcon"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:background="?attr/selectableItemBackgroundBorderless"
            android:padding="@dimen/size_15"
            android:src="@drawable/filter"
            android:visibility="gone" />

        <android.support.design.widget.CoordinatorLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/coor"
            android:layout_centerVertical="true"
            android:layout_toLeftOf="@+id/rightIcon"
            >

            <ImageView
                android:id="@+id/clapIcon"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="?attr/selectableItemBackgroundBorderless"
                android:src="@drawable/clap_star_less_white"
                android:visibility="gone" />

//this clapIconstar view is taken for transition instead of normal
image view in screen do not know

why

            <ImageView
                android:id="@+id/clapIconstar"
                app:layout_anchor="@id/clapIcon"
                app:layout_anchorGravity="left|bottom"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginBottom="@dimen/size_3"
                android:layout_gravity="bottom"
                android:background="?attr/selectableItemBackgroundBorderless"
                android:src="@drawable/star_clap"
                android:layout_marginLeft="@dimen/size_3"
                android:visibility="gone" />
        </android.support.design.widget.CoordinatorLayout>
//this is progress bar
        <FrameLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:layout_margin="@dimen/size_10"
            android:clipChildren="false">

            <include layout="@layout/snap_loader" />
        </FrameLayout>

    </RelativeLayout>

</android.support.v7.widget.Toolbar>
